services:
  trailforkd:
    build: .
    image: sammothxc/trailforkd:latest
    ports:
      - "8080:80"
    environment:
      - CESIUM_ION_TOKEN=
      - TERRAIN_URL=
    networks:
      - internal
    restart: unless-stopped

  terrain-server:
    image: python:3-alpine
    user: "568:568"
    command: python3 -m http.server 8080 --directory /data
    volumes:
      - ./data/terrain-tiles:/data:ro
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
