services:
  trailforkd:
    build: .
    image: ghcr.io/sammothxc/trailforkd:latest
    ports:
      - "8080:80"
    environment:
      - CESIUM_ION_TOKEN=
      - TERRAIN_URL=
      - HEXAGON_URL=
      - DATABASE_URL=postgres://trailforkd:trailforkd@postgres/trailforkd
    networks:
      - internal
    restart: unless-stopped

  terrain-server:
    image: nginx:alpine
    volumes:
      - ./data/terrain-tiles:/usr/share/nginx/html:ro
      - ./nginx/terrain.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    restart: unless-stopped

  postgres:
    image: postgis/postgis:15-3.4-alpine
    environment:
      - POSTGRES_DB=trailforkd
      - POSTGRES_USER=trailforkd
      - POSTGRES_PASSWORD=trailforkd
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - internal
    restart: unless-stopped


networks:
  internal:

volumes:
  postgres-data:
